name: docker

on:
  pull_request:
    paths:
      - Dockerfile
      - rust-toolchain
      - justfile
      - .github/workflows/docker.yml

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: just docker
