name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.md'
      - .github/workflows/markdown.yml

jobs:
  markdownlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - uses: DavidAnson/markdownlint-cli2-action@db43aef879112c3119a410d69f66701e0d530809
        with:
            globs: "**/*.md"
