name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/shellcheck.yml
      - '**/*.sh'
      - justfile

jobs:
  sh-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v30-tools
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - run: just sh-lint
