name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/shellcheck.yml
      - '**/*.sh'
      - justfile

jobs:
  sh-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v30-tools
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: just sh-lint
